"""Browser regressions for selectors generated by exploration snapshots."""

import pytest
import pytest_asyncio
from playwright.async_api import async_playwright

from src.agents.exploratory import _SNAPSHOT_CALLBACK


@pytest_asyncio.fixture
async def page():
    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch(headless=True)
        try:
            yield await browser.new_page()
        finally:
            await browser.close()


@pytest.mark.asyncio
@pytest.mark.parametrize("attributes", [
    'class="w-full hover:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed"',
    'class="w-1/2  text-[#fff]\tbg-black"',
    'id="123:checkout"',
])
async def test_snapshot_selector_clicks_special_character_button(page, attributes):
    await page.set_content(f'<button {attributes} onclick="this.textContent=\'clicked\'">Checkout</button>')
    snapshot = await page.evaluate(_SNAPSHOT_CALLBACK, [])
    selector = snapshot[0]["selector"]
    assert await page.locator(selector).count() == 1
    await page.click(selector)
    assert await page.locator(selector).inner_text() == "clicked"


@pytest.mark.asyncio
async def test_snapshot_selector_matches_quoted_href(page):
    await page.set_content('<a href="/search?q=&quot;hello&quot;">Search</a>')
    snapshot = await page.evaluate(_SNAPSHOT_CALLBACK, [])
    assert await page.locator(snapshot[0]["selector"]).count() == 1


@pytest.mark.asyncio
@pytest.mark.parametrize("tool_name", ["broken_images", "validation_errors", "layout_audit"])
async def test_tool_finding_selector_matches_special_character_element(page, tool_name):
    from src.tools.broken_images import find_broken_images
    from src.tools.layout_audit import _LAYOUT_CALLBACK
    from src.tools.validation_errors import find_validation_errors

    if tool_name == "broken_images":
        await page.set_content('<div id="123:parent"><img class="w-1/2 hover:bg-black" alt="missing"></div>')
        findings = await find_broken_images(page)
    elif tool_name == "validation_errors":
        await page.set_content('<div class="error hover:text-red-500">Invalid input</div>')
        findings = await find_validation_errors(page)
    else:
        await page.set_content('<button class="hover:bg-black" style="width:0;height:0;padding:0;border:0"></button>')
        findings = await page.evaluate(_LAYOUT_CALLBACK, {"maxElements": 300, "heuristics": None})
    assert findings
    for finding in findings:
        assert await page.locator(finding["selector"]).count() == 1
