#!/bin/bash
# Deploy the MCP server wrapper script.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
WRAPPER_PATH="/tmp/qa-agent-mcp-wrapper.sh"

echo "[deploy-mcp] Preparing Python MCP server wrapper…"

cat > "${WRAPPER_PATH}" <<EOF
#!/bin/bash
# MCP QA Agent Wrapper
# AUTO-GENERATED by scripts/deploy-mcp.sh — do not edit manually.
set -euo pipefail
cd "${PROJECT_ROOT}"
exec uv run python -m src.mcp.index "\$@"
EOF

chmod +x "${WRAPPER_PATH}"

echo "[deploy-mcp] ✅ Wrapper updated: ${WRAPPER_PATH}"
echo "[deploy-mcp] ✅ Entry point: ${PROJECT_ROOT}/src/mcp/index.py"
